# What is NumPy ?

----   Numpy is a python package which stands for  "Numerical Python" and it is a general-purpose array-processing package

In [1]:
### why we use numpy:-
# Numpy provides efficient storage.
# It also provides better ways of handling data for processing.
# it is fast.
# easy to learn.
# Numpy usess relatively less memory to store

In [2]:
# One dimensional array - is reffered to as VECTOR
# Two dimensional array - is reffered to as MATRIX
# Three dimensional array - is reffered to as TENSOR

# What is an array ?

An array is a collection of items stored at contiguous memory locations.


In [3]:
# -all of the same type
# -indexed by a tuple of nonnegetive integer
# -arrays are mutable


In [4]:
import numpy as np

In [5]:
array=np.array([1,2,3]) ## this is one dimensional array
print(array)

[1 2 3]


In [6]:
array2=np.array([[1,2,3,4,5,6]])
print(array2)

[[1 2 3 4 5 6]]


-----     here we are doing indexing of array

In [7]:
array[0]

1

In [8]:
array2[0,2]

3

----- now we are chaning the elements of array

In [9]:
array[0]=5
print(array)

[5 2 3]


In [10]:
array2[0,2]=78
print(array2)

[[ 1  2 78  4  5  6]]


# There are 5 mechanisms for creating arrays:

In [11]:
# Conversion from other python structure (eg. list, tuples)
# Intrincs numpy array creation object (eg. arange, ones, zeros, etc.)
# Reading array from disk, either from standard or custome formats
# Creating array from raw bites through the use of string or buffers 
# Use of special library function(eg. random)


## 1.Conversion from other python structure (eg. list, tuples)

In [12]:
listarry = np.array([[1,2,3],[4,5,6],[7,8,9]]) ### creating array with list
listarry

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
listarry.dtype

dtype('int32')

In [14]:
listarry.size

9

In [15]:
listarry.shape

(3, 3)

In [16]:
# just an exmaple - creating array with set ( but only use for numerical and float)

array2=np.array({1,2,3,4,5})
print(array2)

{1, 2, 3, 4, 5}


In [17]:
array2.dtype

dtype('O')

# 2. Intrincs numpy array creation object (eg. arange, ones, zeros, etc.) 

**-- ZEROS**

In [18]:
zero=np.zeros((1,2))
zero

array([[0., 0.]])

In [19]:
zero.shape

(1, 2)

In [20]:
zero.size

2

In [21]:
zero.dtype

dtype('float64')

**-- arange**

In [22]:
arange=np.arange(1,10)
arange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arange.shape

(9,)

In [24]:
arange.size


9

In [25]:
arange.dtype

dtype('int32')

**-- linspace**

In [26]:
linspace=np.linspace(2,10,5)
linspace

array([ 2.,  4.,  6.,  8., 10.])

In [27]:
linspace.shape

(5,)

In [28]:
linspace.size


5

In [29]:
linspace.dtype

dtype('float64')

In [30]:
## if you want to change the data type of this code

linspace=np.linspace(2,10,5, dtype=int)
print(linspace)

[ 2  4  6  8 10]


**-- empty**

In [31]:
empty=np.empty((3,4))     ### here we are creating empty array - it will enter random numbers in array
empty

array([[1.28075779e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.18831764e-312, 5.21645426e-037, 2.00335512e-052,
        1.31425101e-047],
       [1.69094660e-052, 2.46489847e+184, 1.81460368e-052,
        2.25409853e+184]])

# Reshape and ravel functions 

In [32]:
## Use of RESHAPE

**The reshape function is used to change the shape of an array, i.e., it rearranges the elements of an array to give it a new shape.**

In [33]:
rangee=np.arange(1,100)   # suppose we an array
rangee

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
rangee.reshape(3,33)  ## it will convert that into 2 dimentional array and seprate into 3 parts 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66],
       [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
        83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99]])

In [35]:
## ravel function

**used to change a 2-dimensional array or a multi-dimensional array into a contiguous flattened array**

In [36]:
rangee=rangee.reshape(3,33)
rangee

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66],
       [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
        83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99]])

In [37]:
rangee

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66],
       [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
        83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99]])

In [38]:
## now we use ravel function to convert this into one dimensional array or flattened array

In [39]:
rangee.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Functions

**Sum functions**

In [40]:
ar= np.array([[1,2,3],[4,5,6],[10,2,4]])
ar


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10,  2,  4]])

In [41]:
ar.sum()   ## applying sum function

37

In [42]:
array.sum(axis=0) ## applying sum function on axis = 0

10

In [43]:
ar.sum(axis=1)  ## appyling sum funciton on axis = 1

array([ 6, 15, 16])

**Argmax**

  --- it will give that index where is maximum value situated

In [44]:
array10 = np.array ([1,2,3,4,5,6])

In [45]:
array10.argmax()

5

**Argmin**

--- it also give that index where is the minimum value situated

In [46]:
array10.argmin()

0

**Argsort**

In [47]:
array10.argsort()  ## it is also giving index after sorting

array([0, 1, 2, 3, 4, 5], dtype=int64)

# Methods and attributes

----   Transpose

In [48]:
## Using transpose ( always use capital to transpose )
ar.T

array([[ 1,  4, 10],
       [ 2,  5,  2],
       [ 3,  6,  4]])

--- Flat

In [49]:
ar.flat  ### it will flat your complete array and with the help of for loop you can print that

In [50]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
10
2
4


---- ndim

In [51]:
ar.ndim  ### it will show how many dimensions in your array

2

In [52]:
ar.nbytes  ## it will show how much space is consuming your array

36

  # ----------------------------Matrix operation in numpy-----------------------------

In [53]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10,  2,  4]])

In [55]:
ar2=np.array([[4,5,6],[12,7,8],[12,40,1]])
ar2

array([[ 4,  5,  6],
       [12,  7,  8],
       [12, 40,  1]])

**------------------------Applying arthmatic operations between two arrays-----------------**

In [56]:
ar+ar2

array([[ 5,  7,  9],
       [16, 12, 14],
       [22, 42,  5]])

In [57]:
ar*ar2

array([[  4,  10,  18],
       [ 48,  35,  48],
       [120,  80,   4]])

In [59]:
ar2-ar

array([[ 3,  3,  3],
       [ 8,  2,  2],
       [ 2, 38, -3]])

In [60]:
ar/ar2

array([[0.25      , 0.4       , 0.5       ],
       [0.33333333, 0.71428571, 0.75      ],
       [0.83333333, 0.05      , 4.        ]])

In [61]:
ar.sum()

37

In [62]:
ar.max()

10

In [63]:
ar.min()

1

**How can we find a element in array ?**

In [64]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10,  2,  4]])

In [69]:
np.where(ar==10)    ## it will return a tuple of array

(array([2], dtype=int64), array([0], dtype=int64))

**Counting non-zero element in array**

In [75]:
np.count_nonzero(ar)

9

**Counting the elements with zeros**

In [77]:
(ar.size)-(np.count_nonzero(ar))  ## formula creation

0